version: "3"
services:
  web:
    image: "amadeuscam/adra_web"
    mem_limit: 128m
    hostname: web
    environment:
      - DEBUG=$DEBUG
      - SECRET_KEY=$SECRET_KEY
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - SENTRY_SDK_URL=$SENTRY_SDK_URL
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - CELERY_USER=$CELERY_USER
      - CELERY_PASSWORD=$CELERY_PASSWORD
      - SENDGRID_TEMPLATE_ID=$SENDGRID_TEMPLATE_ID
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - Token_KEY_USER=$Token_KEY_USER
      - DATABASE_NAME=$DATABASE_NAME
      - DEFAULT_EMAIL=$DEFAULT_EMAIL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
      - DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
      - REDIS_URL=$REDIS_URL

  # celery:
  #   image: "amadeuscam/adra_web"
  #   mem_limit: 128m
  #   hostname: celery
   
  # celery-beat:
  #   image: "amadeuscam/adra_web"
  #   mem_limit: 128m
  #   hostname: celery-beat

  nginx:
    image: "amadeuscam/adra_nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"