version: "3"

services:
  web:
    build:
      context: .
    command: "gunicorn adra_project.wsgi --bind  0.0.0.0:8000"
    hostname: web
    volumes:
      - static:/static/
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    image: "530212850979.dkr.ecr.eu-west-3.amazonaws.com/django-ec2:nginx"
    hostname: nginx
    volumes:
      - static:/static/
    depends_on:
      - web
    ports:
      - "80:80"
      - 443:443

volumes:
  static: {}
