name: Django Test

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  # build:

  #   runs-on: ubuntu-latest
  #   strategy:
  #     max-parallel: 4
  #     matrix:
  #       python-version: [3.6]

  #   services:
  #     mysql:
  #       image: mysql:5.7
  #       env:
  #         MYSQL_ROOT_PASSWORD: root
  #         MYSQL_DATABASE: mysql
  #       ports: ['3306:3306']

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.6
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.6
  #   - name: Install Dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #   - name: Run Migrations
  #     run: python manage.py migrate
  #     env: 
  #       mysql_user: lucian
  #       mysql_password: masina
  #       SECRET_KEY: 1$$*08nt$$1zy=5&+_vmdhfu7j5#*w_yb9_%+0q7gvr=v)t-51o_

       
  #   - name: Run Tests
  #     run: |
  #       python manage.py test
  #     env: 
  #       mysql_user: lucian
  #       mysql_password: masina
  #       SECRET_KEY: 1$$*08nt$$1zy=5&+_vmdhfu7j5#*w_yb9_%+0q7gvr=v)t-51o_
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Adra App Digital Ocean
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}

          script: |
            cd /home/lucian/adra-t/
            git pull
            echo 'masina' | sudo -S  supervisorctl restart  gunicorn
            echo 'Deployment successful to digital ocean'
