# Generated by Django 2.1.2 on 2019-12-25 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroz_blanco', models.IntegerField(blank=True, null=True)),
                ('garbanzo_cocido', models.IntegerField(blank=True, default=0, null=True)),
                ('atun_sardina', models.IntegerField(blank=True, null=True)),
                ('sardina', models.IntegerField(blank=True, default=0, null=True)),
                ('pasta_espagueti', models.IntegerField(blank=True, default=0, null=True)),
                ('tomate_frito', models.IntegerField(blank=True, null=True)),
                ('galletas', models.IntegerField(blank=True, null=True)),
                ('macedonia_verdura_conserva', models.IntegerField(blank=True, default=0, null=True)),
                ('fruta_conserva_pera', models.IntegerField(blank=True, default=0, null=True)),
                ('fruta_conserva_coctel', models.IntegerField(blank=True, default=0, null=True)),
                ('tarito_pollo', models.IntegerField(blank=True, null=True)),
                ('tarito_fruta', models.IntegerField(blank=True, null=True)),
                ('leche', models.IntegerField(blank=True, null=True)),
                ('batido_chocolate', models.IntegerField(blank=True, null=True)),
                ('aceite_de_oliva', models.IntegerField(blank=True, null=True)),
                ('fecha_recogida', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_recogida'],
            },
        ),
        migrations.CreateModel(
            name='AlmacenAlimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arroz_blanco', models.IntegerField(blank=True, null=True)),
                ('garbanzo_cocido', models.IntegerField(blank=True, default=0, null=True)),
                ('atun_sardina', models.IntegerField(blank=True, null=True)),
                ('sardina', models.IntegerField(blank=True, default=0, null=True)),
                ('pasta_espagueti', models.IntegerField(blank=True, default=0, null=True)),
                ('tomate_frito', models.IntegerField(blank=True, null=True)),
                ('galletas', models.IntegerField(blank=True, null=True)),
                ('macedonia_verdura_conserva', models.IntegerField(blank=True, default=0, null=True)),
                ('fruta_conserva_pera', models.IntegerField(blank=True, default=0, null=True)),
                ('fruta_conserva_coctel', models.IntegerField(blank=True, default=0, null=True)),
                ('tarito_pollo', models.IntegerField(blank=True, null=True)),
                ('tarito_fruta', models.IntegerField(blank=True, null=True)),
                ('leche', models.IntegerField(blank=True, null=True)),
                ('batido_chocolate', models.IntegerField(blank=True, default=0, null=True)),
                ('aceite_de_oliva', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parentesco', models.CharField(choices=[('esposo', 'Esposo'), ('esposa', 'Esposa'), ('hijo', 'Hijo'), ('hija', 'Hija')], default='', max_length=20)),
                ('sexo', models.CharField(choices=[('ninguno', 'Ninguno'), ('mujer', 'Mujer'), ('hombre', 'Hombre')], default='', max_length=20)),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('edad', models.IntegerField(default=0)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=100, verbose_name='Nombre del beneficiario')),
                ('dni', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_adra', models.IntegerField(default=0)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('domicilio', models.TextField()),
                ('are_acte', models.BooleanField(default=False, verbose_name='Tiene papeles')),
                ('ciudad', models.CharField(max_length=350)),
                ('telefono', models.IntegerField()),
                ('mensaje', models.TextField(default='')),
                ('active', models.BooleanField(default=True, verbose_name='Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sexo', models.CharField(choices=[('ninguno', 'Ninguno'), ('mujer', 'Mujer'), ('hombre', 'Hombre')], default='', max_length=20)),
                ('discapacidad', models.BooleanField(default=False)),
                ('domingo', models.CharField(choices=[('Domingo 1', 'domingo1'), ('Domingo 2', 'domingo2')], default='', max_length=30)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('empadronamiento', models.BooleanField(default=False, verbose_name='Certificado de empadronamiento actualizado con fecha de menos de tres meses ')),
                ('libro_familia', models.BooleanField(default=False, verbose_name='Fotocopia del Libro de Familia ')),
                ('fotocopia_dni', models.BooleanField(default=False, verbose_name='Fotocopia del DNI/NIE o pasaporte de todos los miembros del núcleo familiar')),
                ('prestaciones', models.BooleanField(default=False, verbose_name='Fotocopia de la documentación que acredite de prestación, pensión, paro, etc')),
                ('nomnia', models.BooleanField(default=False, verbose_name='Fotocopia de la nómina en caso de trabajar.')),
                ('cert_negativo', models.BooleanField(default=False, verbose_name='En caso de no tener ingresos: certificado negativo de rentas, de la Agencia Tributaria.')),
                ('aquiler_hipoteca', models.BooleanField(default=False, verbose_name='Ultimo recibo alquiler o  hipoteca de vivienda familiar en la que están empadronados')),
                ('recibos', models.BooleanField(default=False, verbose_name='Recibo de gastos básicos: luz, agua, gas, calefacción, comunidad y  comedor escolar.')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hijo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijo', to='adra.Persona'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='adra.Persona'),
        ),
    ]
