# Generated by Django 2.1.2 on 2020-01-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='parentesco',
            field=models.CharField(choices=[('esposo', 'Esposo'), ('esposa', 'Esposa'), ('hijo', 'Hijo'), ('hija', 'Hija')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='sexo',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domingo',
            field=models.CharField(choices=[('Domingo 1', 'domingo1'), ('Domingo 2', 'domingo2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_adra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=20),
        ),
    ]
