# Generated by Django 2.1.2 on 2020-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0002_cambiar_datatime_a_datefield_en_hijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domingo',
            field=models.CharField(choices=[('Domingo 1', '1'), ('Domingo 2', '2')], max_length=30),
        ),
    ]
