# Generated by Django 2.1.2 on 2020-01-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0003_cambiar_chose_domingo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(choices=[('Torrejon de ardoz', 'Torrejon de ardoz')], max_length=350),
        ),
    ]
