# Generated by Django 2.1.2 on 2020-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0004_change_domigopordomingoseparado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domingo',
            field=models.CharField(choices=[('1', 'Domingo 1'), ('2', 'Domingo 2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
