# Generated by Django 2.1.2 on 2020-04-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0006_auto_20200308_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='aceite_de_oliva',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='arroz_blanco',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='atun_sardina',
            field=models.IntegerField(default=None, verbose_name='Atun'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='batido_chocolate',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='fruta_conserva_coctel',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='fruta_conserva_pera',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='galletas',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='garbanzo_cocido',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='leche',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='macedonia_verdura_conserva',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='pasta_espagueti',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='sardina',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='tarito_fruta',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='tarito_pollo',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='tomate_frito',
            field=models.IntegerField(default=None),
        ),
    ]
