# Generated by Django 2.1.2 on 2020-06-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0008_auto_20200517_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
