# Generated by Django 2.1.2 on 2020-06-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0009_add_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Email beneficiario'),
        ),
    ]
