# Generated by Django 2.1.2 on 2020-06-27 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0010_admint_null_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.EmailValidator()], verbose_name='Email beneficiario'),
        ),
    ]
