# Generated by Django 3.0.5 on 2020-07-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0014_persona_covid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='covid',
            field=models.BooleanField(default=False, verbose_name='Covid entregas'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
