# Generated by Django 3.0.5 on 2020-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0015_auto_20200711_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='fecha_recogida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
