# Generated by Django 3.0.5 on 2020-07-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0016_auto_20200711_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='hijo',
            name='dni',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
