# Generated by Django 2.1.2 on 2020-07-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0017_auto_20200712_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='fecha_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
    ]
