# Generated by Django 2.1.2 on 2020-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0018_alimentos_fecha_caducidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='fecha_caducidad',
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='fecha_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
    ]
