# Generated by Django 2.1.2 on 2020-07-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0019_auto_20200722_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='fecha_caducidad',
            new_name='aceite_de_oliva_caducidad',
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='arroz_blanco_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='atun_sardina_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='batido_chocolate_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='fruta_conserva_coctel_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='galletas_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='garbanzo_cocido_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='leche_pollo_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='macedonia_verdura_conserva_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='pasta_espagueti_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='sardina_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='tarito_fruta_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='tarito_pollo_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='tomate_frito_caducidad',
            field=models.DateField(blank=True, default=None),
        ),
    ]
