# Generated by Django 2.1.2 on 2020-07-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0020_auto_20200722_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='leche_pollo_caducidad',
            new_name='leche_caducidad',
        ),
    ]
