# Generated by Django 2.1.2 on 2020-07-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0021_auto_20200722_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenalimentos',
            name='arroz_blanco',
            field=models.IntegerField(blank=True, null=True, verbose_name='Arroz Blanco'),
        ),
    ]
