# Generated by Django 2.1.2 on 2020-07-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0022_auto_20200722_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='arroz_blanco',
            new_name='alimento_1',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='aceite_de_oliva_caducidad',
            new_name='alimento_10_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='arroz_blanco_caducidad',
            new_name='alimento_11_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='atun_sardina_caducidad',
            new_name='alimento_12_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='batido_chocolate_caducidad',
            new_name='alimento_13_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='fruta_conserva_coctel_caducidad',
            new_name='alimento_14_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='galletas_caducidad',
            new_name='alimento_15_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='garbanzo_cocido_caducidad',
            new_name='alimento_1_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='leche_caducidad',
            new_name='alimento_2_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='macedonia_verdura_conserva_caducidad',
            new_name='alimento_3_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='pasta_espagueti_caducidad',
            new_name='alimento_4_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='sardina_caducidad',
            new_name='alimento_6_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='tarito_fruta_caducidad',
            new_name='alimento_7_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='tarito_pollo_caducidad',
            new_name='alimento_8_caducidad',
        ),
        migrations.RenameField(
            model_name='almacenalimentos',
            old_name='tomate_frito_caducidad',
            new_name='alimento_9_caducidad',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='aceite_de_oliva',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='arroz_blanco',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='atun_sardina',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='batido_chocolate',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='fruta_conserva_coctel',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='fruta_conserva_pera',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='galletas',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='garbanzo_cocido',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='leche',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='macedonia_verdura_conserva',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='pasta_espagueti',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='sardina',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='tarito_fruta',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='tarito_pollo',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='tomate_frito',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='aceite_de_oliva',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='atun_sardina',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='batido_chocolate',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='fruta_conserva_coctel',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='fruta_conserva_pera',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='galletas',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='garbanzo_cocido',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='leche',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='macedonia_verdura_conserva',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='pasta_espagueti',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='sardina',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='tarito_fruta',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='tarito_pollo',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='tomate_frito',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_1',
            field=models.IntegerField(default=None, verbose_name='Arroz Blanco'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_10',
            field=models.IntegerField(default=None, verbose_name='Fruta en conserva'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_11',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles con pollo'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_12',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles de fruta'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_13',
            field=models.IntegerField(default=None, verbose_name='Leche entera UHT'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_14',
            field=models.IntegerField(default=None, verbose_name='Batidos de chocolate'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_15',
            field=models.IntegerField(default=None, verbose_name='Aceite de oliva'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_2',
            field=models.IntegerField(default=None, verbose_name='Alubia cocida'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_3',
            field=models.IntegerField(default=None, verbose_name='Conserva de atún'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_4',
            field=models.IntegerField(default=None, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_5',
            field=models.IntegerField(default=None, verbose_name='Conserva de carne (magro de cerdo)'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_6',
            field=models.IntegerField(default=None, verbose_name='Pasta alimenticia tipo macarrón'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_7',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_8',
            field=models.IntegerField(default=None, verbose_name='Galletas'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_9',
            field=models.IntegerField(default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fruta en conserva'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarritos infantiles con pollo'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarritos infantiles de fruta'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leche entera UHT'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_14',
            field=models.IntegerField(blank=True, null=True, verbose_name='Batidos de chocolate'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_15',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aceite de oliva'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alubia cocida'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conserva de atún'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conserva de carne (magro de cerdo)'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pasta alimenticia tipo macarrón'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tomate frito en conserva'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Galletas'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Macedonia de verduras en conserva'),
        ),
    ]
