# Generated by Django 2.1.2 on 2020-07-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0023_auto_20200723_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_5',
            field=models.IntegerField(blank=True, default=None, verbose_name='Conserva de carne (magro de cerdo)'),
        ),
    ]
