# Generated by Django 2.1.2 on 2020-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0024_auto_20200724_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_5',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Conserva de carne (magro de cerdo)'),
        ),
    ]
