# Generated by Django 2.1.2 on 2020-07-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0025_auto_20200724_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo?'),
        ),
    ]
