# Generated by Django 2.1.2 on 2020-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0027_auto_20200726_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
