# Generated by Django 2.1.2 on 2020-07-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0028_auto_20200731_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
