# Generated by Django 2.1.2 on 2020-09-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0029_auto_20200731_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
