# Generated by Django 2.1.2 on 2021-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0031_auto_20201106_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alimentos',
            options={'ordering': ['-fecha_recogida'], 'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='almacenalimentos',
            options={'verbose_name': 'Almacen Alimento', 'verbose_name_plural': 'Almacen Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='hijo',
            options={'verbose_name': 'Familiar del Beneficiario', 'verbose_name_plural': 'Familiares del Beneficiario'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ('-created_at',), 'verbose_name': 'Beneficiario', 'verbose_name_plural': 'Beneficiarios'},
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='alimento_13',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='alimento_14',
        ),
        migrations.RemoveField(
            model_name='alimentos',
            name='alimento_15',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_13',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_13_caducidad',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_14',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_14_caducidad',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_15',
        ),
        migrations.RemoveField(
            model_name='almacenalimentos',
            name='alimento_15_caducidad',
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_5_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tomate frito en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_10',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles de fruta'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_11',
            field=models.IntegerField(default=None, verbose_name='Leche entera UHT'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_12',
            field=models.IntegerField(default=None, verbose_name='Aceite de oliva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_2',
            field=models.IntegerField(default=None, verbose_name='Garbanzos cocidos'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_4',
            field=models.IntegerField(default=None, verbose_name='Pasta alimenticia tipo espagueti'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_5',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_6',
            field=models.IntegerField(default=None, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_7',
            field=models.IntegerField(default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_8',
            field=models.IntegerField(default=None, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_9',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles con pollo'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarritos infantiles de fruta'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_10_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tarritos infantiles de fruta'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leche entera UHT'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_11_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Leche entera UHT'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aceite de oliva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_12_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Aceite de oliva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Garbanzos cocidos'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_2_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Garbanzos cocidos'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pasta alimenticia tipo espagueti'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_4_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Pasta alimenticia tipo espagueti'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tomate frito en conserva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_6_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_7_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_8_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarritos infantiles con pollo'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_9_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tarritos infantiles con pollo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='domingo',
            field=models.CharField(choices=[('1', 'Domingo 2'), ('2', 'Domingo 4')], max_length=30),
        ),
    ]
