# Generated by Django 3.2.10 on 2022-01-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0035_rename_domingo_persona_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='hijo',
            name='otros_documentos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hijo',
            name='dni',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
