# Generated by Django 3.2.10 on 2022-01-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0036_auto_20220123_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Formato fecha-> dia/mes/año'),
        ),
    ]
