# Generated by Django 3.2.10 on 2022-02-13 09:14

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0037_alter_hijo_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='signature',
            field=jsignature.fields.JSignatureField(default=''),
        ),
    ]
