# Generated by Django 3.2.10 on 2022-02-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0038_alimentos_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentos',
            name='signature',
        ),
    ]
