# Generated by Django 3.2.10 on 2022-02-13 09:31

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0039_remove_alimentos_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='signature',
            field=jsignature.fields.JSignatureField(default=None),
        ),
    ]
