# Generated by Django 3.2.10 on 2022-05-01 08:06

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0040_alimentos_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='signature',
            field=jsignature.fields.JSignatureField(blank=True, default=None, null=True),
        ),
    ]
